// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebdtrwkrelzbtjdwuxbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImViZHRyd2tyZWx6YnRqZHd1eGJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMTkzNDMsImV4cCI6MjA2NzU5NTM0M30.QF9dIdUDtliy6o5y2a230vYMwia9qaiAG2TwQj5I9vo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});